load("@rules_zig//zig:defs.bzl", "zig_library", "zig_test")

_SRCS = [
    "error.zig",
    "index.zig",
    "match.zig",
    "decoder.zig",
    "encoder.zig",
]

zig_library(
    name = "index",
    main = "root.zig",
    srcs = _SRCS,
    import_name = "index",
    visibility = ["//visibility:public"],
    deps = [
        "//src/plumbing",
        "//src/plumbing/filemode",
        "//src/plumbing/hash",
        "//src/utils/binary",
    ],
)

zig_test(
    name = "index_test",
    size = "small",
    main = "root.zig",
    srcs = _SRCS,
    deps = [
        "//src/plumbing",
        "//src/plumbing/filemode",
        "//src/plumbing/hash",
        "//src/utils/binary",
    ],
)

filegroup(
    name = "package_srcs",
    srcs = glob(["**/*"]),
    visibility = ["//visibility:public"],
)
