exports_files(
    glob(["**/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all",
    srcs = glob(["**/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "goldens",
    srcs = glob(["goldens/**/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "fixtures",
    srcs = glob(["fixtures/**/*"]),
    visibility = ["//visibility:public"],
)
